update and fix storybook
ir-engine/etherealengine-archive pull request #10021
Opened 2024-04-02 17:34 UTC by DanielBelmes

## Summary

## References
closes #_insert number here_

## QA Steps

2024-04-04 00:11 UTC, speigg approved these changes

2024-04-04 00:13 UTC, speigg requested changes, later dismissed
```ts
> etherealengine@0.0.0 storybook
> cd packages/ui && npm run storybook


> @etherealengine/ui@1.6.0 storybook
> ./scripts/start-storybook.sh

../../.env.local: line 18: Engine: command not found
../../.env.local: line 133: syntax error near unexpected token `newline'
../../.env.local: line 133: `SMTP_FROM_EMAIL=<ENTER_SENDER_EMAIL>'
@storybook/cli v8.0.5

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
SB_CORE-SERVER_0007 (MainFileEvaluationError): Storybook couldn't evaluate your .storybook/main.ts file.

Error: Cannot find module 'storybook-addon-sass-postcss/package.json'
Require stack:
- /.storybook/main.ts
- /Users/gheric/GitHub/etherealengine/node_modules/@storybook/core-server/node_modules/@storybook/core-common/dist/index.js
- /Users/gheric/GitHub/etherealengine/node_modules/@storybook/core-server/dist/index.js
- /Users/gheric/GitHub/etherealengine/node_modules/@storybook/cli/dist/generate.js
- /Users/gheric/GitHub/etherealengine/node_modules/@storybook/cli/bin/index.js
- /Users/gheric/GitHub/etherealengine/node_modules/storybook/index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._resolveFilename (/Users/gheric/GitHub/etherealengine/node_modules/esbuild-register/dist/node.js:4799:36)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at getAbsolutePath (/.storybook/main.ts:119:26)
    at Object.<anonymous> (/.storybook/main.ts:49:5)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._compile (/Users/gheric/GitHub/etherealengine/node_modules/esbuild-register/dist/node.js:2258:26)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.newLoader [as .ts] (/Users/gheric/GitHub/etherealengine/node_modules/esbuild-register/dist/node.js:2262:9)
    at Module.load (node:internal/modules/cjs/loader:1119:32)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

Edit:
NVM; I must have forgotten to `npm install` first.

2024-04-04 00:29 UTC, DanielBelmes commented
@speigg wish we could automate a little message for reviewers that dependencies changed

2024-04-04 00:30 UTC, speigg approved these changes

2024-04-05 18:42 UTC, HexaField approved these changes

2024-04-05 18:43 UTC, merged