fix(magic-link): Fix guest identity provider removal upon login token validation and retain only the latest generated token
ir-engine/etherealengine-archive pull request #10078
Opened 2024-04-18 21:01 UTC by kattsushi

## Summary

This PR addresses two key issues:

Ensures that upon validation of a login token, the guest identity provider is removed from the user. After setup, the identity-provider table will contain only one entry for users logging in via SSO, with any previous guest entries being deleted. However, for email logins, the identity-provider table incorrectly retains the guest entry, which is now resolved to remove the guest entry once the user logs in using a magic link.

Resolves the problem of duplicate tokens being generated for the same user in the login-token service. Now, when a duplicate token is generated, the previously generated token is properly removed.

## Subtasks Checklist

## Breaking Changes

## References
closes [#IR-1290](https://tsu.atlassian.net/browse/IR-1290)

## QA Steps

2024-04-18 21:10 UTC, kattsushi commented
@cla-bot check

2024-04-19 15:41 UTC, hanzlamateen requested changes
I still see the guest identity provider there for email after I verified it using magic link as you can see in row 2 and 3 of below image. Though when I logged it with linkedin SSO the guest entry for it was deleted.

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/55aae53e-1709-49c9-aa37-7e2f4ed5af32)

2024-04-24 18:14 UTC, kattsushi commented
> I still see the guest identity provider there for email after I verified it using magic link as you can see in row 2 and 3 of below image. Though when I logged it with linkedin SSO the guest entry for it was deleted.
> 
> ![image](https://private-user-images.githubusercontent.com/10975502/324022770-55aae53e-1709-49c9-aa37-7e2f4ed5af32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5ODI2NjcsIm5iZiI6MTcxMzk4MjM2NywicGF0aCI6Ii8xMDk3NTUwMi8zMjQwMjI3NzAtNTVhYWU1M2UtMTcwOS00OWM5LWFhMzctN2UyZjRlZDVhZjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE4MTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3ZDVjZjFhYTFlODhiMDEzMzlkNWM0YTA1NjdlYzVhODYzYWFhNTgwZmMwMGI5Njg3NDUwNWRiNmQzNzExNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9XzBDIQqPrpLkxZWZo83bwmi_rMX9swcMHXG_owguVI)

thanks for your comments and help @hanzlamateen this is already fixed

![Screenshot 2024-04-24 at 9 43 52](https://github.com/EtherealEngine/etherealengine/assets/12107518/2b57f9e7-87b9-4415-bf8e-f7f64ccba7c8)

2024-04-25 07:03 UTC, hanzlamateen requested changes

2024-04-25 07:03 UTC, hanzlamateen commented on packages/server-core/src/user/magic-link/magic-link.class.ts
>  with the License. You may obtain a copy of the License at
It seems like currently, it removing guest identity-provider when a magic link is send. This is not correct. The guest identity provider should be removed when a user login using url that he got in his email.

Please have a look of chat we had regarding making these changes in `login.class.ts`

2024-04-29 06:18 UTC, hanzlamateen commented
@kattsushi I just tried and its still now working after I login using magic link. I see 2 entries for same user as in below image

Please share video recording next time and show database entries as well.

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/2bcb094a-83fa-4642-9844-9b56629710d1)

2024-04-29 06:22 UTC, hanzlamateen approved these changes

2024-04-29 06:22 UTC, merged