Improve mac os onboarding, disable minio, and update mediasoup
ir-engine/etherealengine-archive pull request #10071
Opened 2024-04-16 23:29 UTC by DanielBelmes

## Summary

## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-04-17 00:26 UTC, HexaField requested changes
Unfortunately changing the storage provider breaks our server tests in CI/CD. We need to fix this before merging this PR.

2024-04-17 00:37 UTC, DanielBelmes commented
> Unfortunately changing the storage provider breaks our server tests in CI/CD. We need to fix this before merging this PR.

Right!!!! I couldn't remember why we didn't do it. Maybe I'll spend a little time fixing that. It's worth it. If I can find a. Quick solution.

2024-04-22 14:59 UTC, barankyle approved these changes

2024-04-22 22:23 UTC, HexaField approved these changes

2024-04-22 22:24 UTC, merged