Michael/ir 594 postprocessing
ir-engine/etherealengine-archive pull request #10108
Opened 2024-04-30 21:15 UTC by MbfloydIR

Improve PostProcessing API

Added the missing post processing effects

GodRaysEffect needs light source that is not available, so it is left out

The following effects are aded but no difference can be seen when applied

SMAAEffect
SSAOEffect
SSREffect
DepthOfFieldEffect
BloomEffect
SSGIEffect
TRAAEffect
MotionBlurEffect
ShockWaveEffect

2024-05-01 00:15 UTC, DanielBelmes commented
@MbfloydIR you have some errors on the checks here btw. Double check your commit hooks are running.

2024-05-01 19:23 UTC, DanielBelmes requested changes
Some small stuff at first but I believe we do have to refactor configure Effect composer into the PostProcessingComponent earlier than expected for the texture effects.

2024-05-01 19:23 UTC, DanielBelmes commented on packages/editor/src/components/properties/PostProcessingSettingsEditor.tsx
> +    kernelSize: { propertyType: PropertyTypes.KernelSize, name: 'KernelSize' },
The min max and step for this was slightly correct. I actually think there is a KernelSelect we could use for this with values from 0-5. There are others that can use it too.

2024-05-01 19:23 UTC, DanielBelmes commented on packages/spatial/src/renderer/effects/PostProcessing.ts
>  export const defaultPostProcessingSchema: EffectPropsSchema = {
Were you able to check if the default values for the other effects matched the default values from the library/demos?

2024-05-01 19:23 UTC, DanielBelmes commented on packages/spatial/src/renderer/functions/configureEffectComposer.ts
> +        let textLoad = new TextureLoader()
@MichaelEstes Do you have anyway with the resourceManager to load something out of a reactor?

2024-05-01 19:23 UTC, DanielBelmes commented on packages/spatial/src/renderer/functions/configureEffectComposer.ts
> +          AddPass()
I believe you're creating multiple duplicates of the EffectPass with `AddPass()`. We have to refactor this logic into PostProcessingComponent so we can use useEffects and the resource manager in order to load these textures.

2024-05-02 21:44 UTC, HexaField requested changes

2024-05-02 21:44 UTC, HexaField commented on packages/spatial/src/renderer/components/PostProcessingComponent.tsx
> +      //configureEffectComposer(
we should definitely keep this as a separate function, long useEffects are hard to read

2024-05-03 23:53 UTC, HexaField requested changes
we should add a supreactor for each of the effects, we can then react to them individually, as well as simplify the logic around the texture loading

2024-05-07 22:59 UTC, HexaField requested changes

2024-05-07 22:59 UTC, HexaField commented on packages/spatial/src/renderer/components/PostProcessingComponent.tsx
> +    const rendererEntity = useScene(Engine.instance.viewerEntity)
why this change? this means any asset panels will not have postprocessing and apply it to the main canvas

2024-05-20 02:41 UTC, HexaField commented
closing in favour of continued work https://github.com/EtherealEngine/etherealengine/pull/10148

2024-05-20 02:41 UTC, closed without merging