Add project id to location and instance table
ir-engine/etherealengine-archive pull request #10123
Opened 2024-05-03 06:45 UTC by hurairahmateen

## Summary
- Add project id to location and instance table.
- Created migrations to add projectId column.
- Updated service calls to include projectId

## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-05-08 01:51 UTC, hanzlamateen requested changes

2024-05-08 01:51 UTC, hanzlamateen commented on packages/server-core/src/networking/instance/instance.resolvers.ts
> +        if (locationData) {
If there is no locationData then it should throw an error.

2024-05-08 01:51 UTC, hanzlamateen commented on packages/server-core/src/networking/instance/instance.resolvers.ts
> +      throw new BadRequest('Error populating projectId into instance')
Do a log error of `instance` object here for later debugging.

2024-05-08 01:51 UTC, hanzlamateen commented on packages/server-core/src/social/location/location.resolvers.ts
> +      throw new BadRequest('Failed to retrieve project ID from scene ID')
Add `location.sceneId` to this message

2024-05-10 10:01 UTC, hanzlamateen approved these changes
Looks good to me. @HexaField can you give it a look as well.

2024-05-13 13:44 UTC, hurairahmateen commented
Done through MT now.

https://github.com/theinfinitereality/eepro-multitenancy/pull/212

2024-05-29 12:02 UTC, hanzlamateen approved these changes

2024-05-29 12:03 UTC, merged