feat(IR-1829-left-navbar): improvements on Accordion Tailwind component
ir-engine/etherealengine-archive pull request #10146
Opened 2024-05-13 01:08 UTC by kattsushi

## Summary
feat(IR-1829-left-navbar): improvements on Accordion Tailwind component
## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-05-13 12:49 UTC, hanzlamateen approved these changes
Looks good to me, though @aditya-mitra can give it a second look.

2024-05-13 12:57 UTC, aditya-mitra requested changes

2024-05-13 12:57 UTC, aditya-mitra commented on packages/ui/src/primitives/tailwind/Accordion/index.tsx
> +              {' '}
we should remove this space

2024-05-13 12:57 UTC, aditya-mitra commented on packages/ui/src/primitives/tailwind/Accordion/index.tsx
> +      classNameTitle,
we should use `titleClassName` instead of `classNameTitle`

2024-05-14 03:53 UTC, aditya-mitra approved these changes
LGTM

2024-05-14 07:12 UTC, hanzlamateen approved these changes

2024-05-14 07:13 UTC, merged

2024-05-14 08:29 UTC, HexaField commented
@hanzlamateen this PR introduced type errors