fix: Reparenting Transform applied based on the new Parent Transform
ir-engine/etherealengine-archive pull request #10161
Opened 2024-05-14 20:55 UTC by heysokam

## Summary

## Subtasks Checklist

## Breaking Changes

## References

## QA Steps

2024-05-14 21:31 UTC, HexaField requested changes

2024-05-14 21:31 UTC, HexaField commented on packages/editor/src/functions/EditorControlFunctions.ts
> +            .copy(entityTransform.matrix)
both of these might need to be `matrixWorld`

2024-05-15 12:38 UTC, heysokam commented on packages/editor/src/functions/EditorControlFunctions.ts
> +            .copy(entityTransform.matrix)
Changed at 9e40a4e2895fefe353d0842c67354ddaca67d436

2024-05-15 22:53 UTC, HexaField approved these changes

2024-05-15 22:57 UTC, merged