feat(setup): update logo and components props
ir-engine/etherealengine-archive pull request #10204
Opened 2024-05-21 06:17 UTC by mikeplascdev

#### Pull request type

- [x] Bug Fix
- [x] Enhancement
- [ ] Documentation

### Description

- Update logos
- Add new props to the Accordion and Button components

### Figma
[Console-Design](https://www.figma.com/design/a3qQCRxNWxP7K1titmso0e/Console-Design?node-id=0-1&t=kNnJ9JHwCzbr7Ik7-0)

### Evidence

https://github.com/theinfinitereality/eepro-multitenancy/assets/113119956/22858014-8f00-4a91-9f4e-62c1375d8f9b

### Jira
[IR-2119](https://tsu.atlassian.net/browse/IR-2119)

[IR-2119]: https://tsu.atlassian.net/browse/IR-2119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-05-21 10:31 UTC, HexaField requested changes

2024-05-21 10:31 UTC, HexaField commented on packages/client/scripts/getClientSettings.ts
> +        title: 'IR Engine Console',
Should read just `IR Engine`

2024-05-21 15:34 UTC, hanzlamateen approved these changes

2024-05-22 16:56 UTC, mikeplascdev commented on packages/client/scripts/getClientSettings.ts
> +        title: 'IR Engine Console',
Done

2024-05-22 21:26 UTC, HexaField commented
I'd like @aditya-mitra 's eyes on this before we merge in, as there are some changes to the tailwind primitives.

2024-05-23 06:28 UTC, aditya-mitra requested changes
Looks good!
A small modification in the tailwind button would be nice.

2024-05-23 06:28 UTC, aditya-mitra commented on packages/ui/src/primitives/tailwind/Button/index.tsx
> +  variant?: 'primary' | 'outline' | 'danger' | 'success' | 'pink' | 'transparent' | 'onboarding' | 'sidebar'
Is a `sidebar` variant present in the primitive figma designs? 
We should only add colour variant which are primitives. (I plan to refactor the `onboarding` variant)

For any other variant, we should add it as a separate derived button. Something like this
```tsx
const SidebarButton = (props: ButtonProps) => <Button className='bg-[#141619] {...props} />
```

2024-05-23 10:23 UTC, hanzlamateen approved these changes

2024-05-23 10:27 UTC, hanzlamateen commented on packages/ui/src/primitives/tailwind/Button/index.tsx
> +  variant?: 'primary' | 'outline' | 'danger' | 'success' | 'pink' | 'transparent' | 'onboarding' | 'sidebar'
I am merging this PR for now as I want to deploy this in MT. @mikeplascdev can you please address aditya's concern in a separate PR.

2024-05-23 10:27 UTC, merged

2024-05-25 20:50 UTC, DanielBelmes commented
Since the urls have stayed the same. We won't be able to see the updated assets on domains we visited before. In my PR I added query parameters to the urls to cache bust them. Whoever is giving demos Wednesday needs to clear their cache to be able to see these changes. @hanzlamateen