fixCSMandLightReactivity
ir-engine/etherealengine-archive pull request #10213
Opened 2024-05-21 23:02 UTC by DanielBelmes

## Summary

## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-05-22 18:12 UTC, DanielBelmes commented
comment from @HexaField **"instead of passing the rendererSettingsEntity down, we should rearrange it such that rather than querying for the RendererSettingscomponent, and mounting a CSM reactor tree for each, it should be for each RendererComponent we want a CSM reactor tree, that uses useChildWithComponent to get an entity in the scene with a render settings component."**

2024-05-24 02:06 UTC, dinomut1 requested changes
This does make CSM reactive at least to the properties, but it also breaks it further.

Here is loading electronics store scene on dev. You can see for a moment CSM is there with somewhat correct values before getting overridden or something:
[Screencast from 05-23-2024 07:01:56 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/3edfcba5-240c-4d37-aeaf-cb063af2b83a)

Here is the same scene when loaded in this branch:
[Screencast from 05-23-2024 07:03:13 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/97e4928c-daff-4e6b-9c77-7cf42ce5d0c5)

2024-05-24 06:09 UTC, HexaField requested changes

2024-05-24 06:09 UTC, HexaField commented on packages/engine/src/scene/systems/ShadowSystem.tsx
> +  const entities = useHookstate(useTreeQuery(props.rendererEntity))
wrapping useHookstate around this is an anti pattern. the data already updates reactively

2024-05-24 06:09 UTC, HexaField commented on packages/engine/src/scene/systems/ShadowSystem.tsx
> +    if (groupComponent) {
let's do an early opt out rather than nested

2024-05-24 06:09 UTC, HexaField commented on packages/engine/src/scene/systems/ShadowSystem.tsx
> +  const renderSettingsEntity = useChildWithComponent(rendererEntity, RenderSettingsComponent)
the same number of hooks must always exist in a reactor, move the early escape after all hooks

2024-05-24 16:53 UTC, DanielBelmes commented on packages/engine/src/scene/systems/ShadowSystem.tsx
> +  const renderSettingsEntity = useChildWithComponent(rendererEntity, RenderSettingsComponent)
Dang. I'll try again but this passes an UndefinedEntity to useComponent and causes some infintie suspend behavior.

2024-05-24 16:55 UTC, DanielBelmes commented on packages/engine/src/scene/systems/ShadowSystem.tsx
> +  const entities = useHookstate(useTreeQuery(props.rendererEntity))
Then I believe we have a bug within useTreeQuery. Specifically that we map through it's results with the Number constructor. I believe we might be derefrencing the results. I gotta test today.

2024-05-24 17:13 UTC, DanielBelmes commented on packages/engine/src/scene/systems/ShadowSystem.tsx
> +  const renderSettingsEntity = useChildWithComponent(rendererEntity, RenderSettingsComponent)
Oh sorry misunderstood. Was confusing some changes I never pushed with this comment

2024-05-24 18:31 UTC, DanielBelmes commented on packages/engine/src/scene/systems/ShadowSystem.tsx
> +  const entities = useHookstate(useTreeQuery(props.rendererEntity))
nvm I was dumb with keys

2024-05-25 20:51 UTC, dinomut1 approved these changes
working better than what we have. Still have weird cascade offset though

2024-05-25 20:51 UTC, merged