feat(assets): update styles [IR-2272]
ir-engine/etherealengine-archive pull request #10318
Opened 2024-06-05 05:48 UTC by mikeplascdev

## Summary

- Update the styles for the asset panel
- Create a breadcrumb for the assets
- back functionality
- refresh functionality
- fix the resource list

## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

## Evidence

https://github.com/EtherealEngine/etherealengine/assets/113119956/25959302-9a0e-451a-a6f6-aadc05a361b3

[IR-2272](https://tsu.atlassian.net/browse/IR-2272)
[Figma](https://www.figma.com/design/DXwFHGa5g0peqqSjyjpxQz/Studio-(Public-Preview-Milestone)?node-id=4358-3369&t=Y29Htp53DCGR9D9S-4)

[IR-2272]: https://tsu.atlassian.net/browse/IR-2272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-06-05 18:48 UTC, jonathan-casarrubias commented
LGTM but test checks are failing, can you check that

2024-06-06 05:08 UTC, aditya-mitra requested changes
Looks good functionality wise!

we should remove this white space
![image](https://github.com/EtherealEngine/etherealengine/assets/55396651/8c9701ef-57f0-49b6-b377-905d7d627c2c)

2024-06-06 05:08 UTC, aditya-mitra commented on packages/ui/src/components/editor/panels/Assets/container/index.tsx
> +            containerClassname="flex h-full bg-theme-primary rounded-[4px] w-auto"
suggestion: instead of `rounded-[4px]` we can use tailwind values `rounded` which is shorthand

2024-06-06 05:15 UTC, aditya-mitra approved these changes
Looks and works awesome 🤩

2024-06-06 05:15 UTC, merged