migrate prefab list
ir-engine/etherealengine-archive pull request #10329
Opened 2024-06-05 23:41 UTC by JT00y

## Summary
migrate prefab list button to hierarchy panel 
## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-06-06 08:01 UTC, aditya-mitra requested changes
Looks good. Just a few comments.

2024-06-06 08:01 UTC, aditya-mitra commented on packages/ui/src/components/editor/panels/Hierarchy/prefabList/index.tsx
> +      <Icon className="h-6 w-6 text-white" />
we should use [react-icons](react-icons.github.io/react-icons) corresponding icon instead of mui-icons

2024-06-06 08:01 UTC, aditya-mitra commented on packages/ui/src/components/editor/panels/Hierarchy/prefabList/index.tsx
> +  }
can you please remove these commented lines?

2024-06-06 08:01 UTC, aditya-mitra commented on packages/ui/src/components/editor/panels/Hierarchy/prefabList/index.tsx
> +          />
add `inputRef={inputReference}` here for auto focus on open

2024-06-07 11:09 UTC, aditya-mitra requested changes

2024-06-07 11:09 UTC, aditya-mitra commented on packages/ui/src/components/editor/panels/Hierarchy/prefabList/index.tsx
> +export default PrefabList
this new prefab list is almost similar to [elementList](https://github.com/EtherealEngine/etherealengine/blob/1c68aaa125ad23ba0288d35bee8541eb50174c08/packages/ui/src/components/editor/panels/Properties/elementList/index.tsx)

The only difference here is the action performed when a prefab item is clicked from the list and the name of the list being prefab list.

We should make the element list dynamic to reduce code duplication.

2024-06-07 12:22 UTC, aditya-mitra approved these changes

2024-06-10 19:52 UTC, dinomut1 approved these changes
good

2024-06-10 19:53 UTC, merged