studio: new settings menu ui
ir-engine/etherealengine-archive pull request #10478
Opened 2024-06-28 15:40 UTC by achen5671

## Summary

## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-07-01 04:25 UTC, aditya-mitra requested changes
the client settings menu is in the location route which uses the old material ui currently and not tailwind. which happens to break the ui

do we have the design already for the user menu?

![image](https://github.com/EtherealEngine/etherealengine/assets/55396651/44026ea9-f3f8-4d23-97c5-41b94a12e683)

2024-07-01 04:28 UTC, aditya-mitra commented
merged with current dev which has tailwind planted in all routes. the select menus and tabs are non-functional and the modals appear broken

![image](https://github.com/EtherealEngine/etherealengine/assets/55396651/61cefef4-7908-4347-947d-853c4b42a9c2)

2024-07-01 13:39 UTC, achen5671 commented
> merged with current dev which has tailwind planted in all routes. the select menus and tabs are non-functional and the modals appear broken
> 
> ![image](https://private-user-images.githubusercontent.com/55396651/344542896-61cefef4-7908-4347-947d-853c4b42a9c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDEzNTAsIm5iZiI6MTcxOTg0MTA1MCwicGF0aCI6Ii81NTM5NjY1MS8zNDQ1NDI4OTYtNjFjZWZlZjQtNzkwOC00MzQ3LTk0N2QtODUzYzRiNDJhOWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEzMzczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZTU0N2FhMGYwZjRkODFjZjJlN2M1MjMxNTVhNDZjODVhNjIyMDcwMzk4Njk0NDA4YzBmMGE4M2FmNmFmNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.epX31uYAezetIOcsgrMIfJ_1LHnBJdAw7lw4xx_JYsg)

The last time I check the select menu has always been broken. I created a separate ticket to address the issue which I will take a look at. This PR just updates the UI.

2024-07-01 17:03 UTC, achen5671 commented
> > merged with current dev which has tailwind planted in all routes. the select menus and tabs are non-functional and the modals appear broken
> > ![image](https://private-user-images.githubusercontent.com/55396651/344542896-61cefef4-7908-4347-947d-853c4b42a9c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDEzNTAsIm5iZiI6MTcxOTg0MTA1MCwicGF0aCI6Ii81NTM5NjY1MS8zNDQ1NDI4OTYtNjFjZWZlZjQtNzkwOC00MzQ3LTk0N2QtODUzYzRiNDJhOWMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEzMzczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1ZTU0N2FhMGYwZjRkODFjZjJlN2M1MjMxNTVhNDZjODVhNjIyMDcwMzk4Njk0NDA4YzBmMGE4M2FmNmFmNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.epX31uYAezetIOcsgrMIfJ_1LHnBJdAw7lw4xx_JYsg)
> 
> The last time I check the select menu has always been broken. I created a separate ticket to address the issue which I will take a look at. This PR just updates the UI.

fixed ui

2024-07-03 18:21 UTC, achen5671 commented
I updated it to use the Modal component. I also broke out the new settings to it's own component called settings2 like we talked about. Let me know if there are any other changes you will like :)

2024-07-08 23:02 UTC, HexaField requested changes, later dismissed

2024-07-08 23:02 UTC, HexaField commented on packages/client-core/src/user/UserUISystem.tsx
>        [UserMenus.Settings]: SettingMenu,
If the old settings menu is not being used anymore, we should remove it and replace it with this new one.

2024-07-08 23:03 UTC, HexaField commented on packages/client-core/src/user/UserUISystem.tsx
>        [UserMenus.Settings]: SettingMenu,
Oh sorry, I see that this new one is to be used in tailwind routes instead, is that correct?

2024-07-16 12:40 UTC, achen5671 commented
@aditya-mitra per up on our talk last week. Im using the MUI modal here for now to be compatible with the location route. 

Our current modal isn't compatible but in the near future we should update our current modal so that it is.

pr is ready for rereview

2024-07-22 12:47 UTC, aditya-mitra approved these changes
awesome 🚀

2024-07-22 14:07 UTC, merged