disallow project query without pagination
ir-engine/etherealengine-archive pull request #10577
Opened 2024-07-10 23:35 UTC by HexaField

## Summary

We no longer are using the project service from the client without pagination, so we should disallow this to avoid causing considerable load on the server if someone was to request this.

## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-07-11 09:07 UTC, hanzlamateen requested changes

2024-07-11 09:07 UTC, hanzlamateen commented on packages/common/src/schemas/projects/project.schema.ts
> -        paginate: Type.Optional(Type.Boolean()),
I see it being still used in:

1. https://github.com/EtherealEngine/etherealengine/blob/dd999046f9f6c30089f8e4df12d045d47fe588d8/packages/editor/src/components/projects/ProjectsPage.tsx#L200
2. https://github.com/EtherealEngine/etherealengine/blob/dd999046f9f6c30089f8e4df12d045d47fe588d8/packages/ui/src/components/editor/panels/Files/container/index.tsx#L195
3.

2024-07-11 09:28 UTC, HexaField commented on packages/common/src/schemas/projects/project.schema.ts
> -        paginate: Type.Optional(Type.Boolean()),
@hanzlamateen I have addressed both of these. The file browser has been optimized to only look for the two possible values, and the projects page is only used in single tenant and requires client pagination UI

2024-07-11 09:51 UTC, hanzlamateen requested changes

2024-07-11 09:51 UTC, hanzlamateen commented on packages/ui/src/components/editor/panels/Files/container/index.tsx
> +  const [orgName, projectName] = path.split('/').slice(2, 3)
@HexaField I don't think we get `projectName` for MT/orgname scenarios:

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/dcab43d9-1455-48a6-a8fe-64c5088739ab)

2024-07-12 10:06 UTC, hanzlamateen approved these changes

2024-07-12 10:06 UTC, merged