Changes to NotificationService and UseRealtime hook
ir-engine/etherealengine-archive pull request #10664
Opened 2024-07-19 04:21 UTC by MoizAdnan

Changes to NotificationService:
- Returns enqueued snackbar key
- Adds option for persisting notifications
- Adds option to close a notification with snackbar key
- Adds ReactNode as mesage type

UseRealtime hook now works for custom events

2024-07-19 05:30 UTC, HexaField commented on packages/spatial/src/common/functions/FeathersHooks.tsx
> +    if (customEvent) {
what custom events do we have?

2024-07-19 06:06 UTC, hanzlamateen requested changes

2024-07-19 06:06 UTC, hanzlamateen commented on packages/client-core/src/common/services/NotificationService.tsx
> +  dispatchNotify(message: string | React.ReactNode, options: NotificationOptions) {
```suggestion
  dispatchNotify(message: React.ReactNode, options: NotificationOptions) {
```

2024-07-19 06:06 UTC, hanzlamateen commented on packages/client-core/src/common/services/NotificationService.tsx
> +    if (options?.variant === 'error' && typeof message === 'string') {
Why do we need `&& typeof message === 'string'`

2024-07-22 10:45 UTC, hanzlamateen approved these changes

2024-07-22 10:45 UTC, merged