Remove old editor files and UI elements
ir-engine/etherealengine-archive pull request #10695
Opened 2024-07-22 19:58 UTC by SYBIOTE

This pull request removes old editor files, updates the editor name and route, and removes various panels, dialogs, layouts, and UI elements that are no longer needed. These changes help to slim down the visual script UI and remove unused components.

2024-07-22 23:51 UTC, HexaField commented
Nice work, still failing errors though

2024-07-23 04:52 UTC, SYBIOTE commented
Ill fix it up

2024-07-23 06:34 UTC, CITIZENDOT commented
These packages can be removed from `packages/editor/package.json`:
- react-hot-keys
- rc-slider

2024-07-23 09:28 UTC, hanzlamateen commented
Also, I think following files are redundant:

1. packages/client-core/src/admin/common/Location/LocationDrawer.tsx (It was previously used to publish locations from studio)
2. packages/client-core/src/admin/common/Project/ProjectDrawer.tsx (I do see it being used in studio's project page, but I wonder is we can use the dialog used in admin panel to get rid of this old UI drawer based control). If we get rid of this then following can be removed as well
  a. packages/client-core/src/admin/common/DrawerView.tsx
  b. packages/client-core/src/admin/common/validation/formValidation.ts

2024-07-23 11:40 UTC, aditya-mitra commented
adding a few code comments for files which have moved or have changed lines. this will help us better understand what happened to the older lines. (ideally, remove old editor files means deletions of files)

2024-07-23 11:41 UTC, aditya-mitra commented on packages/editor/src/components/assets/useUpload.tsx
> -import { ProgressDialog } from '../dialogs/ProgressDialog'
All of these were not functioning in the new UI. Also, a full refactor of the useUpload function is needed.

2024-07-23 11:42 UTC, aditya-mitra commented on packages/client/src/pages/editor/index.tsx
> +import { EditorPage, useStudioEditor } from '@etherealengine/editor/src/pages/EditorPage'
renamed tailwind `Editor2Page` to `EditorPage`

2024-07-23 11:43 UTC, aditya-mitra commented on packages/editor/src/components/EditorContainer.css
> +/** references https://github.com/ticlo/rc-dock/blob/master/dist/rc-dock.css */
renamed `Editor2Container.css` as `EditorContainer.css` and moved the contents from `Editor2Container.css` to here

2024-07-23 11:43 UTC, aditya-mitra commented on packages/editor/src/components/EditorContainer.tsx
same for this. renamed. moved contents from `Editor2Container.tsx` to `EditorContainer.tsx`

2024-07-23 11:44 UTC, aditya-mitra commented on packages/editor/src/components/dialogs/ImportSettingsPanelDialog.tsx
renaming

2024-07-23 11:45 UTC, aditya-mitra commented on packages/editor/src/components/dialogs/SaveSceneDialog.tsx
removed `SaveSceneDialog2.tsx` to `SaveSceneDialog` and moved contents from `SaveSceneDialog2.tsx` to here

2024-07-23 11:52 UTC, aditya-mitra commented on packages/editor/src/components/toolbar/Toolbar.tsx
> +import { SaveNewSceneDialog, SaveSceneDialog } from '../dialogs/SaveSceneDialog'
import changes due to file movement

2024-07-23 11:53 UTC, aditya-mitra commented on packages/editor/src/components/visualScript/VisualScriptUIModule.ts
> -export * from './components/modals/SaveModal'
deleted components

2024-07-23 11:53 UTC, aditya-mitra commented on packages/editor/src/pages/EditorPage.tsx
`Editor2Page` renamed as `EditorPage` and contents of `Editor2Page` moved here

2024-07-23 11:54 UTC, aditya-mitra commented on packages/editor/src/systems/ModelHandlingSystem.ts
> +import { ImportSettingsState } from '../services/ImportSettingsState'
import changes

2024-07-23 11:54 UTC, aditya-mitra commented on packages/editor/src/systems/UploadRequestSystem.tsx
> +import { ImportSettingsState } from '../services/ImportSettingsState'
import changes

2024-07-23 11:55 UTC, aditya-mitra commented on packages/projects/default-project/xrengine.config.ts
remove old studio and studio now imports from renamed pages/editor

2024-07-23 11:58 UTC, aditya-mitra commented on packages/editor/src/services/ImportSettingsState.ts
this file is just written with `ImportSettingsState` which was earlier present in `ImportSettingsPanel`

2024-07-23 12:00 UTC, aditya-mitra commented on packages/projects/default-project/xrengine.config.ts
removed old studio path

2024-07-23 12:02 UTC, aditya-mitra commented on packages/editor/src/services/ImportSettingsState.ts
this file is just written with ImportSettingsState which was earlier present in ImportSettingsPanel

2024-07-23 21:29 UTC, dinomut1 submitted a review, later dismissed
This is gonna break several projects. We need to add linked PRs for
https://github.com/theinfinitereality/irpro-wizard.git
https://github.com/theinfinitereality/eepro-ecommerce-tools.git
https://github.com/theinfinitereality/eepro-xrui-components.git
before merging them all in together

2024-07-24 06:52 UTC, aditya-mitra commented
yes here they are:
- https://github.com/theinfinitereality/eepro-ecommerce-tools/pull/97
- https://github.com/theinfinitereality/eepro-multitenancy/pull/360
- https://github.com/theinfinitereality/irpro-wizard/pull/6
- https://github.com/theinfinitereality/eepro-xrui-components/pull/24

2024-07-24 12:56 UTC, aditya-mitra commented
> packages/client-core/src/admin/common/Project/ProjectDrawer.tsx (I do see it being used in studio's project page, but I wonder is we can use the dialog used in admin panel to get rid of this old UI drawer based control). If we get rid of this then following can be removed as well
a. packages/client-core/src/admin/common/DrawerView.tsx

only these 2 will be removed later once the projects page is refactored into tailwind (currently just used in single tenant dev)

2024-07-24 20:54 UTC, dinomut1 commented
is the ecommerce branch ready for merge yet? once that's ready i think we're good to go

2024-07-25 03:17 UTC, HexaField requested changes
![Screenshot from 2024-07-25 13-16-56](https://github.com/user-attachments/assets/ae2563fd-9148-4092-a4d3-60ed3f391499)

something doesnt look right. maybe its using the wrong themeing? or from merging dev in?

2024-07-25 09:38 UTC, aditya-mitra commented
> is the ecommerce branch ready for merge yet? once that's ready i think we're good to go

yes it is

2024-07-25 14:40 UTC, CITIZENDOT commented
> something doesnt look right. maybe its using the wrong themeing? or from merging dev in?

Just checked this on a fresh install and I don't see this glitch. [Something similar happened to me before](https://github.com/EtherealEngine/etherealengine/pull/10542#issuecomment-2220276539), but it went away after cleaning node_modules and reinstalling them.

2024-07-29 08:25 UTC, HexaField approved these changes
Amazing work.

2024-07-29 08:58 UTC, merged