[IR-3322] studio: update ArrayInputGroup to improve usability and accept dropped files
ir-engine/etherealengine-archive pull request #10706
Opened 2024-07-23 16:22 UTC by dtlehrer

## Summary
[IR-3322] now able to drag & drop files into ArrayInputGroup

## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

[IR-3322]: https://tsu.atlassian.net/browse/IR-3322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-07-23 22:29 UTC, dinomut1 requested changes, later dismissed
[Screencast from 07-23-2024 03:27:34 PM.webm](https://github.com/user-attachments/assets/8c8a91e8-7d66-4de3-b69f-5f39910af1e2)
Can't drag and drop onto individual array items, instead it just adds it to the list. 
There should be an additional drop area in the URL field of each individual list item that lets you change the url for that item

2024-07-24 04:32 UTC, dtlehrer commented
> [Screencast from 07-23-2024 03:27:34 PM.webm](https://github.com/user-attachments/assets/8c8a91e8-7d66-4de3-b69f-5f39910af1e2) Can't drag and drop onto individual array items, instead it just adds it to the list. There should be an additional drop area in the URL field of each individual list item that lets you change the url for that item

updated to handle this case as well:
https://github.com/user-attachments/assets/29cf7a40-cb70-4065-aee9-0647b333b854

2024-07-24 06:14 UTC, aditya-mitra requested changes
seeing an anamoly when updating the first item

https://github.com/user-attachments/assets/5efa38f9-5138-45be-9a8b-75d8d2295384

2024-07-24 06:14 UTC, aditya-mitra commented on packages/ui/src/components/editor/input/Array/index.tsx
> +      <div ref={dropRef} className={`mb-2 flex items-center ${isDroppable ? 'outline outline-2 outline-white' : ''}`}>
```suggestion
      <div ref={dropRef} className={twMerge('mb-2 flex items-center', isDroppable && 'outline outline-2 outline-white')}>
```

we can utilise twMerge in this cases - it simplifies using normal string

2024-07-24 06:14 UTC, aditya-mitra commented on packages/ui/src/components/editor/input/Array/index.tsx
> +const DiscardableInput = ({ value, index, inputLabel, onChange, onRemove, dropTypes }) => {
```suggestion
const DiscardableInput = ({
  value,
  index,
  inputLabel,
  onChange,
  onRemove,
  dropTypes
}: {
  value: string
  index: number
  onChange: (val: string, idx: number) => void
  onRemove: (idx: number) => void
} & Pick<ArrayInputProps, 'inputLabel' | 'dropTypes'>) => {
```

2024-07-24 12:45 UTC, aditya-mitra approved these changes
awesome bug solving

2024-07-24 12:59 UTC, merged