fix(ir-engine): implemented scene name length validation
ir-engine/etherealengine-archive pull request #10920
Opened 2024-08-08 13:52 UTC by jonathan-casarrubias

## Summary
Implemented scene name length specific validation error message

## Subtasks Checklist

## Breaking Changes

## References
closes #_insert number here_

## QA Steps

2024-08-08 14:54 UTC, mikeplascdev approved these changes

2024-08-08 20:28 UTC, kattsushi approved these changes

2024-08-09 10:08 UTC, CITIZENDOT requested changes

2024-08-09 10:08 UTC, CITIZENDOT commented on packages/common/src/utils/validateSceneName.ts
> +}
This check is not necessary because `VALID_SCENE_NAME_REGEX` enforces min & max checks in the regex itself.

2024-08-09 10:31 UTC, CITIZENDOT requested changes

2024-08-09 10:31 UTC, CITIZENDOT commented on packages/client-core/i18n/en/editor.json
> +    "invalidSceneNameLength": "Invalid input: Name must be between 4 and 64 characters"
there is no need of a new message. Instead, we can rewrite the first message as: 
> Scene name must be 4-64 characters long, using only alphanumeric characters, hyphens, and underscores.

2024-08-09 10:31 UTC, CITIZENDOT commented on packages/editor/src/components/dialogs/SaveSceneDialog.tsx
> +    }
this is not necessary as well

2024-08-09 10:36 UTC, hanzlamateen approved these changes

2024-08-09 10:36 UTC, merged