selection state stores uuid
ir-engine/etherealengine-archive pull request #9696
Opened 2024-01-31 01:44 UTC by HexaField

## Summary

## References
closes #_insert number here_

## QA Steps

2024-01-31 19:00 UTC, dinomut1 requested changes
Running into a crash when chaining reparents
[Screencast from 01-31-2024 01:59:08 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/9a761c21-b1e1-45fa-884d-c74f52b89dca)

2024-02-02 23:04 UTC, dinomut1 requested changes
[Screencast from 02-02-2024 03:02:35 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/0c349d4d-f4a1-4800-869c-d2e364ef0c48)
I'm not able to select things now. Reparenting and stuff works, but the properties panel is not showing selection

2024-02-05 06:17 UTC, HexaField commented
> [Screencast from 02-02-2024 03:02:35 PM.webm](https://github.com/EtherealEngine/etherealengine/assets/94419856/0c349d4d-f4a1-4800-869c-d2e364ef0c48) I'm not able to select things now. Reparenting and stuff works, but the properties panel is not showing selection

resolved

2024-02-05 20:00 UTC, DanielBelmes commented on packages/editor/src/components/element/PropertiesPanelContainer.tsx
> +  const selectedEntities = useHookstate(getMutableState(SelectionState).selectedEntities).value
~~can remove UseHookstate here since it's not used in the useEffect anymore and we're just using its value.~~ Sorry I think it's good as the component will rerender if selectedEntities changes.

2024-02-05 21:12 UTC, speigg approved these changes

2024-02-05 23:34 UTC, merged