Rename master branch to main
ir-engine/etherealengine-archive pull request #9736
Opened 2024-02-09 01:59 UTC by HexaField

## Summary

## References
closes #_insert number here_

## QA Steps

2024-02-15 21:49 UTC, DanielBelmes approved these changes

2024-06-06 21:11 UTC, barankyle approved these changes

2024-06-06 21:41 UTC, barankyle approved these changes

2024-06-06 21:44 UTC, barankyle requested changes
The references to master in update-deps-branch.yml should probably remain as master, since they're referencing outside work.

2024-06-13 23:01 UTC, barankyle approved these changes

2024-06-13 23:01 UTC, merged