seperate visual script from engine into its own package
ir-engine/etherealengine-archive pull request #9764
Opened 2024-02-14 23:58 UTC by SYBIOTE

seperates visual script into its own package with the relevant UI seperate from the editor and engine packages

2024-02-23 23:28 UTC, DanielBelmes commented on packages/visual-script/src/engine/generateUuid.ts
> +  }${lut[(d3 >> 24) & 0xff]}`
@SYBIOTE if we're gonna be generating a uuid might as well use this standard libbrary https://github.com/uuidjs/uuid

2024-02-23 23:37 UTC, HexaField commented on packages/visual-script/src/engine/generateUuid.ts
> +  }${lut[(d3 >> 24) & 0xff]}`
we have uuidv4 and also threejs utility, we should standardize on one of them

2024-02-26 18:43 UTC, DanielBelmes commented on packages/visual-script/src/engine/generateUuid.ts
> +  }${lut[(d3 >> 24) & 0xff]}`
> we have uuidv4 and also threejs utility, we should standardize on one of them

I believe the one I linked is the same as uuidv4. I like that one. It's super standard and will definitly be more secure than three's as it has more users.

2024-03-01 22:26 UTC, DanielBelmes requested changes
Just wanted to bring to your attention the failing checks and merge conflicts

2024-03-03 02:04 UTC, SYBIOTE commented
will handle these, the visual script -tests must be merged into this branch first

2024-03-04 23:25 UTC, DanielBelmes commented
> will handle these, the visual script -tests must be merged into this branch first

Ah understood. I will check out that PR

2024-03-14 12:06 UTC, SYBIOTE commented
its all fixed

2024-03-14 23:22 UTC, merged