Tailwind Migration of Admin Panel
ir-engine/etherealengine-archive pull request #9794
Opened 2024-02-26 08:52 UTC by aditya-mitra

## Summary

- rewrite the admin panel using tailwindcss

## References
closes #_insert number here_

## QA Steps

2024-04-02 09:59 UTC, hanzlamateen commented
1. "Add Avatar" button looks different than other similar buttons. Same goes for action button:

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/235810b2-022a-4394-ba91-093c584f94d7)

They can be updated to match "Create Invite"
![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/b90ca304-2581-4216-b07d-25a9ed3355d9)

Action button can be updated to match the style/alignment of user's table actions:
![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/1b1314eb-42fa-493b-a327-269ab852e327)

This applies to Locations, Instance, Resource pages as well.

2024-04-02 10:19 UTC, CITIZENDOT commented
> 1. "Add Avatar" button looks different than other similar buttons. Same goes for action button. They can be updated to match "Create Invite"
> 
> 2. Action button can be updated to match the style/alignment of user's table actions. This applies to Locations, Instance, Resource pages as well.

Fixed these.

2024-04-02 10:20 UTC, hanzlamateen commented
2. Add project functionality seems to be broken. Its working fine in adminold.

https://github.com/EtherealEngine/etherealengine/assets/10975502/12ec57f0-a8f3-4885-bbfb-e54824139256

2024-04-02 10:25 UTC, hanzlamateen commented
3. In Add Project dialog, copy from source buttons seems missing. Also tooltips in Auto Update are missing. Both these exists in adminold
![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/80ff848b-b7c6-4fb7-81e0-990cfd8580e5)

2024-04-02 10:39 UTC, hanzlamateen requested changes
4. Design of action button appears different in designs and implementation
![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/1b5e474c-7e81-49a4-b13a-621d65c4021d)

2024-04-02 10:44 UTC, hanzlamateen requested changes
5. Order of items in admin menu appears different than in design. Not sure if this is relevant. Also logout button is not in designs.

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/fb7ed183-5c60-4f48-b935-4a0647805e0c)

2024-04-02 10:50 UTC, hanzlamateen commented
> > 1. "Add Avatar" button looks different than other similar buttons. Same goes for action button. They can be updated to match "Create Invite"
> > 2. Action button can be updated to match the style/alignment of user's table actions. This applies to Locations, Instance, Resource pages as well.
> 
> Fixed these.

Still appearing big for Create Location, Patch Instanceserver, Create Resource, Save/Reset button in Settings

2024-04-02 10:53 UTC, hanzlamateen commented
6. In old UI there used to be an exclamation mark next to project name if there was an update for it.

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/9a44a71e-3837-460b-9eb2-a8bd4d50c6f4)

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/4529b6ab-5336-4954-9029-7798664e3b18)

2024-04-02 10:56 UTC, hanzlamateen commented
7. Notification service seems broken in tailwind

https://github.com/EtherealEngine/etherealengine/assets/10975502/0543a242-5ebf-481c-bd7a-f7f069e85c46

2024-04-02 10:58 UTC, hanzlamateen commented
8. `Enabled` column in missing in new Project table. I think this got introduced after designs were created.
![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/c3569fda-e7f7-4f68-b2c5-15281e3e9262)

2024-04-02 11:03 UTC, hanzlamateen commented
9. When trying to delete a project, confirmation dialog appears. Its should show title "Confirmation" to match with other modals. Also I think this `showConfirmDialog` control can be moved to a common place from where it can be used in other components like we used to have `packages/client-core/src/common/components/ConfirmDialog/index.tsx` in old UI

2024-04-02 11:05 UTC, hanzlamateen commented
10. Github Repo Link button seems to be missing. I guess it used to allow "Change Destination Repo"

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/7a632d0d-5198-4904-9442-15842b539837)

2024-04-02 11:26 UTC, hanzlamateen commented
11. I think tag column is no longer required in Locations table.

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/27446473-dbe7-4b9f-8dd4-9fcfa6f8ee33)

2024-04-02 11:32 UTC, hanzlamateen commented
12. View Instance dialog appears quite different than designs

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/6de29fab-e84b-4a5a-8ad8-48dec5c28fda)

2024-04-02 11:35 UTC, hanzlamateen commented
13. Delete instance has wrong title. I think a common control/method should be used across admin panel for this dialogs as discussed in Point 9 above (https://github.com/EtherealEngine/etherealengine/pull/9794#issuecomment-2031709809)

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/159ea175-9c5e-4f3d-8b0e-bdf0118a9fa5)

2024-04-02 12:36 UTC, hanzlamateen commented
14. In add Avatar modal and for all modals header and footer should remain fixed/visible, only content should be scrollable.

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/12d93d33-dbd8-46d9-9e89-cab2418ce201)

2024-04-02 12:42 UTC, hanzlamateen commented
15. Avatar Modal appears different than in design

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/376faf97-3ef1-4415-95f8-ef73d9d3c30c)

2024-04-02 12:50 UTC, hanzlamateen commented
16. In Create Invite Modal:

a. It crashes when you select Instance from the dropdown
b. Make user admin checkbox should only appear for Type: User. Not for instance and location.

https://github.com/EtherealEngine/etherealengine/assets/10975502/fbc59253-baf1-4547-a253-bc4ec3fef0f4

2024-04-02 12:54 UTC, hanzlamateen commented
17. In Invites table:

a. Spawn Type column is missing
b. In actions Delete button is missing
c. Update Invite button's style is different than as in design. Though I think this button's style can be made similar to the design of action buttons in projects table.

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/ff893f2d-fdb1-4b8e-aa77-b9173a1b6300)

2024-04-02 13:21 UTC, hanzlamateen commented
18. In user Page:

  a. Add/Create User button is missing
  b. Last Login & IsGuest columns should be shown as in old admin panel
  c. When you hover over linked account icons it should show the account username in tooltip as shown in image below

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/067b4e4d-3b58-43f3-aa3e-7e9d5be4e9ea)
![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/659514a2-3866-4d28-8aa8-94211563117b)

2024-04-02 13:51 UTC, CITIZENDOT commented
> 18. In user Page:
> 
> a. Add/Create User button is missing b. Last Login & IsGuest columns should be shown as in old admin panel c. When you hover over linked account icons it should show the account username in tooltip as shown in image below

It was discussed to remove `Add User` button here: https://discord.com/channels/692672143053422678/1210546427957084220/1219959481253888061. TLDR: we should not be able to add users manually

2024-04-02 16:32 UTC, hanzlamateen commented
19. Routing in setting page is missing. In our old admin panel, currently selected tab was reflect in URL using # i.e.

https://dev.etherealengine.com/admin/settings#taskServer
https://dev.etherealengine.com/admin/settings#project

2024-04-02 16:54 UTC, hanzlamateen commented
20. Save button is missing in Instance & Task server settings

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/8edd8cf4-7f13-4fad-be79-b602b4a69372)

2024-04-02 17:01 UTC, hanzlamateen commented
21. In Email Settings

a. Secure needs to be under SMTP
b. Labels for fields under Subject needs to be fixed. Caps for login and friend, string for channel.

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/31f0ea4c-a39b-4508-9eec-fe23d6e32410)

2024-04-02 17:09 UTC, hanzlamateen commented
22. Although this is contrary to designs but I think the sub headings in Email should be similar font size as used in Authentication section shown in 2nd image. Looks more clean.

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/5e2fccd0-bdd2-4c6b-91a9-869cde039dcf)
![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/c874b415-57a5-437d-92f1-a008a3065ec2)

2024-04-02 17:09 UTC, CITIZENDOT commented
> 20. Save button is missing in Instance & Task server settings

I removed them since all inputs are disabled all the time. Do we really need them?

2024-04-02 17:18 UTC, hanzlamateen commented
23. Size of Toggle button for Auth Strategies is too big. They can be made to match remaining toggle buttons.

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/f9db896d-1093-4135-ba8a-25e45436d942)

2024-04-02 17:21 UTC, hanzlamateen commented
24. The color of Toggle Button appears to be different than the button. I think they can be made to have similar color as mentioned in designs as well.

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/648740d9-ad89-40ca-a176-939cfe7c1c2a)

2024-04-03 05:54 UTC, hanzlamateen commented
25. There seems to be some inconsistency in modal with as shown below. I think the size of modal as in add project should be the default. For certain specific cases, there should be ability to allow larger size but for most of the use cases add project modal width should be desired.

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/32e45b56-a0b1-469f-9981-36604417c5a2)

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/6943f70f-6182-4ebf-adbc-46bf34564a68)

2024-04-03 06:28 UTC, hanzlamateen commented
26. On server page

a. It seems like there is a scrollbar which makes pagination button hidden
b. View Logs Modal width is not set properly as shown in video.

https://github.com/EtherealEngine/etherealengine/assets/10975502/f7a5e143-02b9-441e-a241-8814bb440d82

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/1ad91697-989c-4caf-85c7-b218e3f1ce31)

2024-04-03 06:37 UTC, hanzlamateen commented
27. Status column in build status tab should be a Badge as in designs

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/b8c61dfe-77bd-4c48-88c9-d7c54b0a2190)

2024-04-03 06:42 UTC, hanzlamateen commented
28. On server tab, view logs button in light mode had its color dull.

![image](https://github.com/EtherealEngine/etherealengine/assets/10975502/f7f9d67c-b2bf-4dcf-8e16-75491d94a8c0)

2024-04-04 13:25 UTC, hanzlamateen requested changes

2024-04-04 13:25 UTC, hanzlamateen commented on packages/client-core/src/admin2/common/Table.tsx
> +        <div key={idx} className="h-12 w-full odd:bg-gray-300 even:bg-gray-200" />
We need to ensure pulse handles dark/light mode

2024-04-04 13:25 UTC, hanzlamateen commented on packages/client-core/src/admin2/common/Table.tsx
> +        <div className="absolute left-1/2 top-1/2 flex h-8 -translate-x-1/2 -translate-y-1/2 items-center">
Ideally, we should use `<LoadingView />` control here.

2024-04-04 13:25 UTC, hanzlamateen commented on packages/client-core/src/admin2/components/avatar/AvatarTable.tsx
>            <button
I think we should use tailwind `<Button />` control for all instances of `<button>` in this file.

If there are various button styles, then we should handle it through variants prop.

2024-04-04 13:25 UTC, hanzlamateen commented on packages/client-core/src/admin2/components/channel/ChannelTable.tsx
> +          <button
I think we should use tailwind `<Button />` control for all instances of `<button>` in this file.

If there are various button styles, then we should handle it through variants prop.

2024-04-04 13:25 UTC, hanzlamateen commented on packages/client-core/src/admin2/components/channel/ChannelTable.tsx
> +            onClick={() => PopoverState.showPopupover(<RemoveChannelModal channels={[row]} />)}
Instead of this custom Modal, we should use `showConfirmDialog()`.

2024-04-04 13:25 UTC, hanzlamateen commented on packages/client-core/src/admin2/components/channel/index.tsx
> +                    PopoverState.showPopupover(<RemoveChannelModal channels={selectedChannels.value} />)
Instead of this custom Modal, we should use `showConfirmDialog()`.

2024-04-04 13:25 UTC, hanzlamateen commented on packages/client-core/src/admin2/components/invites/InviteTable.tsx
> +            onClick={() => PopoverState.showPopupover(<RemoveInviteModal invites={[row]} />)}
Instead of this custom Modal, we should use `showConfirmDialog()`.

2024-04-04 13:25 UTC, hanzlamateen commented on packages/client-core/src/admin2/components/invites/index.tsx
> +                    PopoverState.showPopupover(<RemoveInviteModal invites={selectedInvites.value} />)
Instead of this custom Modal, we should use `showConfirmDialog()`.

2024-04-04 13:25 UTC, hanzlamateen commented on packages/client-core/src/admin2/components/locations/LocationTable.tsx
> +          <button
I think we should use tailwind `<Button />` control for all instances of `<button>` in this file.

If there are various button styles, then we should handle it through variants prop.

2024-04-04 13:25 UTC, hanzlamateen commented on packages/client-core/src/admin2/components/project/AddEditProjectModal.tsx
> +                <div className="flex items-center gap-3">
If possible we should use `<LoadingView />` control here and other instances of ui with `<LoadingCirle />` in this file.

2024-04-04 13:25 UTC, hanzlamateen commented on packages/client-core/src/admin2/components/recordings/index.tsx
> +            icon={<HiMagnifyingGlass />}
It seems like this icon prop does not exists on Input component

2024-04-04 13:25 UTC, hanzlamateen commented on packages/client-core/src/admin2/components/server/ServerTable.tsx
> +          <button
I think we should use tailwind `<Button />` control for all instances of `<button>` in this file.

If there are various button styles, then we should handle it through variants prop.

2024-04-04 13:25 UTC, hanzlamateen commented on packages/client-core/src/admin2/components/user/UserTable.tsx
> +            <button
I think we should use tailwind `<Button />` control for all instances of `<button>` in this file.

If there are various button styles, then we should handle it through variants prop.

2024-04-04 13:25 UTC, hanzlamateen commented on packages/client-core/src/admin2/components/user/UserTable.tsx
> +              onClick={() => PopoverState.showPopupover(<RemoveUserModal users={[row]} />)}
Instead of this custom Modal, we should use `showConfirmDialog()`.

2024-04-05 03:51 UTC, aditya-mitra commented on packages/client-core/src/admin2/common/Table.tsx
> +        <div className="absolute left-1/2 top-1/2 flex h-8 -translate-x-1/2 -translate-y-1/2 items-center">
This shows a loading indicator inside the table itself (shown in the image below).
![image](https://github.com/EtherealEngine/etherealengine/assets/55396651/7995a29d-c5b2-49a1-9e5f-4e963c99d41f)
`LoadingView` would appear like this (as shown in the image below)
![image](https://github.com/EtherealEngine/etherealengine/assets/55396651/a48bf981-51a8-43f4-97e0-df55bb9167a1)

2024-04-05 06:31 UTC, aditya-mitra commented on packages/client-core/src/admin2/components/project/AddEditProjectModal.tsx
> +                <div className="flex items-center gap-3">
Since this a fallback text for the first condition not satisfied, we are not using LoadingView here.

2024-04-09 18:54 UTC, HexaField approved these changes
Amazing work everyone

2024-04-09 18:54 UTC, merged