9728 - Audio Analysis Component
ir-engine/etherealengine-archive pull request #9833
Opened 2024-03-04 19:42 UTC by internetcharles

## Summary
Audio analysis component with bass, mid and treble selectors and multipliers.

## References
closes #_insert number here_

## QA Steps

2024-03-04 23:33 UTC, HexaField requested changes

2024-03-04 23:33 UTC, HexaField commented on packages/engine/src/scene/components/AudioAnalysisComponent.ts
> +    if (json.bassEnabled) {
we need to assert `typeof json.property === number` or use `matches.number.test(json.property` otherwise falsy values will not be allowed to be set

2024-03-04 23:33 UTC, HexaField commented on packages/engine/src/scene/components/AudioAnalysisComponent.ts
> +      listenerMesh.material.color = new Color(0xffffff)
where is this mesh being used?

2024-03-04 23:33 UTC, HexaField commented on packages/engine/src/scene/components/AudioAnalysisComponent.ts
> +  jsonID: 'audio-analyzer',
please use `EE_audio_analyzer` format for jsonID

2024-03-04 23:33 UTC, HexaField commented on packages/engine/src/scene/components/AudioAnalysisComponent.ts
> +      setComponent(entity, VisibleComponent)
scene data like `VisibleComponent`, `NameComponent`, `TransformComponent` should be set from the scene JSON rather than set here

2024-03-04 23:33 UTC, HexaField commented on packages/editor/src/components/properties/AudioAnalysisEditor.tsx
> +          onChange={updateProperty(AudioAnalysisComponent, 'midEnabled')}
this needs to be `commitProperty`

2024-03-04 23:33 UTC, HexaField commented on packages/editor/src/components/properties/AudioAnalysisEditor.tsx
> +          onChange={updateProperty(AudioAnalysisComponent, 'trebleEnabled')}
this needs to be `commitProperty`

2024-03-04 23:33 UTC, HexaField commented on packages/editor/src/components/properties/AudioAnalysisEditor.tsx
> +          onChange={updateProperty(AudioAnalysisComponent, 'bassEnabled')}
this needs to be `commitProperty`

2024-03-05 00:59 UTC, dinomut1 approved these changes

2024-03-05 00:59 UTC, merged