Flesh out graphics settings with defaults per device
ir-engine/etherealengine-archive pull request #9921
Opened 2024-03-14 20:24 UTC by MichaelEstes

## Summary
Add graphic settings defaults depending on device hardware
## References
closes #7817 
## QA Steps

2024-03-18 20:57 UTC, DanielBelmes approved these changes

2024-03-19 00:33 UTC, HexaField approved these changes
looks great!

2024-03-19 02:24 UTC, HexaField requested changes
![Screenshot from 2024-03-19 13-23-41](https://github.com/EtherealEngine/etherealengine/assets/10372036/b6f09096-ef10-4ce4-8905-3b28e7323e92)
On my laptop i'm seeing the quality going back and forth between too low and too high, as indicated by the FPS display

2024-03-19 03:45 UTC, HexaField commented
> On my laptop i'm seeing the quality going back and forth between too low and too high, as indicated by the FPS display

actually this seems to happen anyway, looks like this isn't yet hooked up to the graphics "automatic" mode

2024-03-19 03:46 UTC, HexaField approved these changes

2024-03-20 18:17 UTC, merged